# IMPORTS

In [1]:
#IMPORTS
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

## PLAYER_NAMES.CSV

In [2]:
#load up pitchers data
players = pd.read_csv('player_names.csv')

### Select a pitcher and get their ID number

In [3]:
#get id of a given person
lastname = 'Scherzer'
firstname = 'Max'

mypitchers = players[players['last_name']==lastname]

if len(mypitchers) != 1:
    mypitchers = mypitchers[mypitchers['first_name']==firstname]

mypitchers

        id first_name last_name
69  453286        Max  Scherzer

In [4]:
#get id number for a given player and convert to an integer
idtmp = np.array(mypitchers['id'])
id_num = np.ndarray.item(idtmp)
id_num

453286

## ATBATS.CSV

In [5]:
#load up atbats.csv
atbats = pd.read_csv('atbats.csv')

In [6]:
#select all atbats where pitcher_id matches id_num 
#(ie. all at bats where the pitcher is involved in from all at bats)
atbats_pitcher = atbats[atbats['pitcher_id']==id_num]
atbats_pitcher

,ab_id,batter_id,event,g_id,inning,o,p_score,p_throws,pitcher_id,stand,top
631,2015000632,434158,Walk,201500010,1,0,0,R,453286,L,True
632,2015000633,431151,Pop Out,201500010,1,1,0,R,453286,R,True
633,2015000634,446263,Strikeout,201500010,1,2,0,R,453286,L,True
634,2015000635,150212,Groundout,201500010,1,3,0,R,453286,R,True
640,2015000641,502517,Flyout,201500010,2,1,0,R,453286,L,True
...,...,...,...,...,...,...,...,...,...,...,...
734272,2018179458,605119,Pop Out,201802352,6,3,3,R,453286,R,True
734276,2018179462,621446,Strikeout,201802352,7,1,3,R,453286,R,True
734277,2018179463,621573,Strikeout,201802352,7,2,3,R,453286,R,True
734278,2018179464,642423,Single,201802352,7,2,3,R,453286,L,True
734279,2018179465,518618,Flyout,201802352,7,3,3,R,453286,L,True

In [7]:
#creates a year column from ab_id and engineers for input dataframe df
def addYear(df):
    #convert ab_id to string, extract first 4 characters, convert back to int
    df['year'] = df['ab_id'].astype(str).str[0:4].astype(int)
    return df

### Left vs. Right handed batters against this pitcher ID (for every AT BAD)

In [8]:
#left and right handers batters faced by this pitcher for ALL at bats against this pitcher expressed as a percentage
LandR = atbats_pitcher['stand']
LandR.value_counts() / len(LandR) * 100

L    52.492754
R    47.507246
Name: stand, dtype: float64

### Events per AT BAT against this pitcher ID

In [9]:
#Percentage of events per AT BAT
ev_ab = atbats_pitcher['event']
ev_ab.value_counts() / len(ev_ab) * 100

Strikeout              32.637681
Groundout              14.000000
Flyout                 11.594203
Single                 10.347826
Pop Out                 7.565217
Lineout                 5.594203
Walk                    5.362319
Double                  4.144928
Home Run                2.985507
Hit By Pitch            0.985507
Grounded Into DP        0.985507
Forceout                0.811594
Sac Bunt                0.753623
Field Error             0.492754
Triple                  0.405797
Intent Walk             0.289855
Bunt Groundout          0.260870
Sac Fly                 0.231884
Bunt Pop Out            0.173913
Runner Out              0.115942
Double Play             0.086957
Fielders Choice Out     0.086957
Strikeout - DP          0.057971
Fielders Choice         0.028986
Name: event, dtype: float64

In [10]:
#select all at bat id numbers to get from the pitches database
atbat_id = atbats_pitcher['ab_id']
atbat_id.shape

(3450,)

## PITCHES.CSV

In [11]:
#load ALL MLB pitch data for 2015-2018 using pitches.csv
pitches = pd.read_csv('pitches.csv')
pitches.describe()

,px,pz,start_speed,end_speed,spin_rate,spin_dir,break_angle,break_length,break_y,ax,ay,az,sz_bot,sz_top,type_confidence,vx0,vy0,vz0,x,x0,y,y0,z0,pfx_x,pfx_z,nasty,zone,event_num,b_score,ab_id,b_count,s_count,outs,pitch_num,on_1b,on_2b,on_3b
count,2.852965e+06,2.852965e+06,2.853040e+06,2.853040e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.865071e+06,2.865071e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.852965e+06,2.867154e+06,2.852965e+06,2.867154e+06,2.852965e+06,2.852965e+06,2.853012e+06,2.853012e+06,2.852965e+06,2.852965e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06,2.867154e+06
mean,6.572502e-03,2.254962e+00,8.838124e+01,8.136274e+01,1.731173e+03,1.802308e+02,5.848084e+00,6.601459e+00,2.381685e+01,-2.308512e+00,2.649175e+01,-2.278275e+01,1.566689e+00,3.435719e+00,1.550896e+00,2.282811e+00,-1.288567e+02,-4.420795e+00,1.159975e+02,-7.189111e-01,1.758503e+02,5.000000e+01,5.814139e+00,-1.139971e+00,5.046326e+00,4.442669e+01,9.819750e+00,3.129711e+02,2.256608e+00,2.016606e+09,8.824259e-01,8.810873e-01,9.826033e-01,2.894472e+00,3.018314e-01,1.860451e-01,9.595543e-02
std,8.927490e-01,9.463968e-01,6.015540e+00,5.364057e+00,6.827521e+02,6.742859e+01,2.443621e+01,1.331708e+02,6.446540e-02,1.074066e+01,4.142729e+00,8.865066e+00,1.549407e-01,2.172590e-01,5.537377e-01,5.990039e+00,8.726126e+00,3.067389e+00,3.409448e+01,1.728592e+00,2.960411e+01,3.120278e-14,4.578852e-01,6.275731e+00,5.187005e+00,1.683662e+01,4.060956e+00,1.928482e+02,2.550955e+00,1.117238e+06,9.665457e-01,8.251786e-01,8.174947e-01,1.726595e+00,4.590526e-01,3.891431e-01,2.945302e-01
min,-1.054333e+01,-5.183664e+00,3.390000e+01,3.240000e+01,1.214000e+00,-2.000000e-03,-9.000000e+01,1.000000e-01,2.330000e+01,-5.929009e+01,-5.243748e-01,-7.717142e+01,-7.921409e+00,-1.849129e+00,0.000000e+00,-2.486900e+01,-1.533620e+02,-1.977060e+01,0.000000e+00,-9.556000e+00,0.000000e+00,5.000000e+01,-1.941000e+00,-2.809165e+01,-7.020600e+01,0.000000e+00,1.000000e+00,3.000000e+00,0.000000e+00,2.015000e+09,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,-5.908243e-01,1.650000e+00,8.430000e+01,7.790000e+01,1.238745e+03,1.371540e+02,-1.190000e+01,4.300000e+00,2.380000e+01,-1.129000e+01,2.346000e+01,-2.871775e+01,1.485351e+00,3.300000e+00,9.060000e-01,-2.081861e+00,-1.355100e+02,-6.513000e+00,9.342000e+01,-1.955000e+00,1.606500e+02,5.000000e+01,5.564194e+00,-6.450000e+00,2.160000e+00,3.200000e+01,6.000000e+00,1.490000e+02,0.000000e+00,2.016004e+09,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.300000e-02,2.259000e+00,8.970000e+01,8.250000e+01,1.866322e+03,1.958850e+02,6.800000e+00,6.000000e+00,2.380000e+01,-3.142000e+00,2.647444e+01,-2.159500e+01,1.570000e+00,3.440000e+00,2.000000e+00,3.989000e+00,-1.308299e+02,-4.604841e+00,1.161400e+02,-1.333530e+00,1.771800e+02,5.000000e+01,5.842237e+00,-1.880000e+00,6.090000e+00,4.400000e+01,1.100000e+01,3.020000e+02,1.000000e+00,2.017004e+09,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.090000e-01,2.863000e+00,9.300000e+01,8.540000e+01,2.247564e+03,2.252340e+02,2.700000e+01,8.000000e+00,2.390000e+01,5.995827e+00,2.938409e+01,-1.574300e+01,1.658626e+00,3.578467e+00,2.000000e+00,6.625942e+00,-1.229450e+02,-2.488206e+00,1.392400e+02,7.766212e-01,1.936400e+02,5.000000e+01,6.104551e+00,3.864644e+00,8.950000e+00,5.600000e+01,1.300000e+01,4.640000e+02,3.000000e+00,2.018002e+09,2.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
max,1.295291e+01,1.488624e+01,1.050000e+02,9.690000e+01,6.539259e+03,3.600010e+02,2.694000e+02,2.248893e+05,3.640000e+01,4.097800e+01,5.405700e+01,2.230520e+01,1.069854e+01,1.054815e+01,2.000000e+00,2.515000e+01,-4.755200e+01,2.781500e+01,2.499500e+02,9.676000e+00,2.500000e+02,5.000000e+01,1.059600e+01,2.202000e+01,3.316048e+01,1.000000e+02,1.400000e+01,1.336000e+03,2.500000e+01,2.018186e+09,4.000000e+00,2.000000e+00,2.000000e+00,2.100000e+01,1.000000e+00,1.000000e+00,1.000000e+00

In [12]:
#drop all NaNs
pitches.dropna(inplace=True)

### Pitch types thrown by all pitchers (by percentage)

In [13]:
#look at all pitch types thrown by all pitchers
allptypes = pitches['pitch_type']
allptypes.value_counts() / len(allptypes) * 100

FF    35.575274
SL    15.797840
FT    11.844552
CH    10.259830
SI     8.501080
CU     8.215401
FC     5.246325
KC     2.332426
FS     1.528949
KN     0.395469
IN     0.217297
EP     0.028519
FO     0.028449
PO     0.021986
SC     0.003969
UN     0.002002
AB     0.000316
FA     0.000316
Name: pitch_type, dtype: float64

In [14]:
#drop rows of all pitches that are pitchouts/and intentional balls and unknown pitch types
pitchesrmv = ['FO', 'PO', 'IN', 'UN', 'FA', 'AB']

for i in pitchesrmv:
    pitches = pitches[pitches['pitch_type']!=i]

#look at the counts of all pitch types for all pitchers    
pitches['pitch_type'].value_counts()

FF    1012917
SL     449804
FT     337244
CH     292123
SI     242047
CU     233913
FC     149376
KC      66410
FS      43533
KN      11260
EP        812
SC        113
Name: pitch_type, dtype: int64

## Remap all pitch types to 3 categories of pitches

In [15]:
#dictionary for pitch types to reduce pitches for ALL pitches thrown by all pichers
#FB (fastball type pitches) = FF (four-seam fastball), FT (two-seam fastball), FC (cut fastball), SI (sinker), 
#BR (breaking ball type pitches) = SL (slider), CU (curveball), SC (screwball)
#OS (offspeeed type pitches) = CH (change-up), FS (split-finger fastball), KB (knuckleball), EP (eephus)

globalpitchmap = {'FF':'FB', 'SL':'BR', 'FT':'FB', 'CH':'OS', 'SI':'OS', 
                  'CU':'BR', 'FC':'FB', 'KC':'BR', 'FS':'OS', 'KN':'OS', 'EP':'OS', 'SC':'BR'}

pitches = pitches.applymap(lambda s: globalpitchmap.get(s) if s in globalpitchmap else s)
pitches['pitch_type'].value_counts()

FB    1499537
BR     750240
OS     589775
Name: pitch_type, dtype: int64

In [16]:
#show as a percentage
pitches['pitch_type'].value_counts() * 100 / len(pitches['pitch_type'])

FB    52.808929
BR    26.421069
OS    20.770002
Name: pitch_type, dtype: float64

### ALL Pitches belonging to Pitcher ID

In [17]:
#select ALL pitches from the list of AT BATS in atbat_id - these are the pitches thrown by the pitcher
mypitches = pitches[pitches['ab_id'].isin(atbat_id)]
mypitches.describe()

,px,pz,start_speed,end_speed,spin_rate,spin_dir,break_angle,break_length,break_y,ax,ay,az,sz_bot,sz_top,type_confidence,vx0,vy0,vz0,x,x0,y,y0,z0,pfx_x,pfx_z,nasty,zone,event_num,b_score,ab_id,b_count,s_count,outs,pitch_num,on_1b,on_2b,on_3b
count,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,1.338000e+04,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,1.338000e+04,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000,13380.000000
mean,-0.017489,2.361240,89.624387,82.419163,1673.959843,198.667305,19.869993,6.358655,23.811046,-8.997737,26.958029,-22.915845,1.561261,3.434782,1.470263,9.516074,-130.538142,-2.870304,117.344740,-3.054636,174.127513,5.000000e+01,5.262953,-4.842292,4.861523,43.690658,9.280643,220.598356,0.885351,2.016598e+09,0.784604,0.968610,1.001121,2.918685,0.231390,0.128176,0.056129
std,0.872551,0.869663,5.478798,4.672216,815.371869,62.850460,19.621466,2.373280,0.064027,8.295117,4.285221,7.976804,0.162008,0.215788,0.553726,2.604035,7.959973,2.303373,33.408497,0.216850,25.333521,3.254180e-14,0.277126,4.803461,4.338754,16.923182,4.230266,133.742380,1.193954,1.121126e+06,0.924427,0.840026,0.810969,1.760186,0.421737,0.334299,0.230178
min,-3.541925,-1.450000,72.000000,67.500000,2.595000,0.775000,-34.200000,0.500000,23.500000,-27.676654,8.842292,-50.650566,-1.316377,2.572184,0.501000,-1.531000,-144.600000,-11.298000,0.000000,-3.763170,0.000000,5.000000e+01,4.435279,-17.677580,-11.801286,2.000000,1.000000,3.000000,0.000000,2.015001e+09,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,-0.594433,1.821000,85.300000,78.900000,890.161000,184.110500,-2.700000,4.500000,23.800000,-15.417837,23.491836,-30.024249,1.473855,3.290000,0.901000,7.939000,-137.343452,-4.445211,94.692500,-3.207891,158.887500,5.000000e+01,5.072610,-8.539998,1.340000,31.000000,5.000000,107.000000,0.000000,2.016001e+09,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,0.003291,2.407404,92.100000,84.000000,1947.494500,219.831500,25.900000,5.500000,23.800000,-12.372781,27.087814,-20.470000,1.570000,3.433389,2.000000,9.658643,-133.997500,-2.935037,116.610000,-3.050754,173.495000,5.000000e+01,5.238479,-6.664411,6.187390,43.000000,11.000000,214.000000,0.000000,2.016179e+09,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000
75%,0.573334,2.949544,94.300000,86.300000,2323.488000,230.496000,36.000000,8.200000,23.900000,-0.253829,30.231000,-16.276112,1.660000,3.580000,2.000000,11.306085,-124.257827,-1.326620,139.515000,-2.910000,189.380000,5.000000e+01,5.420901,-0.156475,8.319801,55.000000,13.000000,325.000000,1.000000,2.018007e+09,1.000000,2.000000,2.000000,4.000000,0.000000,0.000000,0.000000
max,3.290000,5.955325,98.700000,90.900000,4039.077000,359.842000,88.400000,14.600000,24.200000,17.001735,43.224000,1.103051,2.186665,4.227088,2.000000,18.300000,-105.426000,7.199891,245.530000,-1.428548,249.810000,5.000000e+01,6.836783,12.300596,17.865226,100.000000,14.000000,650.000000,7.000000,2.018179e+09,3.000000,2.000000,2.000000,13.000000,1.000000,1.000000,1.000000

In [18]:
#use this to avoid later problems with having * in the string
mypitches = mypitches.replace('*B','DirtB')

###  Drop UNNECESSARY Columns

In [19]:
#drop unnecessary columns
dropcols = ['start_speed', 'spin_rate', 'spin_dir', 'break_angle', 'break_length', 'break_y',
           'ax', 'ay', 'az', 'sz_bot', 'sz_top', 'type_confidence', 'vx0', 'vy0', 'vz0', 'x', 'x0', 'y',
           'y0', 'z0', 'pfx_x', 'pfx_z', 'nasty', 'zone', 'event_num','code']

mypitches = mypitches.drop(columns=dropcols, axis=1)

### Pitch Type Frequency for Pitcher

In [20]:
#Frequency of pitches thrown by the selected pitcher
mypitchtypes = mypitches['pitch_type']
order = mypitchtypes.value_counts() / len(mypitchtypes) * 100
order

FB    58.445441
BR    27.825112
OS    13.729447
Name: pitch_type, dtype: float64

## LABEL ENCODING

In [21]:
#establish a dictionary for the 3 categories of pitches
pitchmap = {'FB': 1, 'BR': 2, 'OS': 3}

In [22]:
#replace the pitch_type column 2 letter codes with a correspending value from the dictionary pitchmap,
#then add in the old 2 letter column as a guide for later look up

pitchtypetmp = mypitches.copy()['pitch_type']
mypitches = mypitches.applymap(lambda s: pitchmap.get(s) if s in pitchmap else s)
mypitches['pitch_type_code'] = pitchtypetmp
mypitches['pitch_type'] = mypitches['pitch_type'].astype(int)
mypitches.shape

(13380, 15)

### TYPE CONVERSIONS

In [23]:
#convert ab_id to integer
mypitches['ab_id'] = mypitches['ab_id'].astype(int)

In [24]:
#add a years column to mypitches
mypitches = addYear(mypitches)

In [25]:
#Duplicates values from a unique ab_id from a specific at bat (column) from the atbat dataframe
#to another dataframe with multiple instances of ab_id values (multiple values in the same column).

def copyData(from_df, to_df, atbatidlist, column_name):
    newcol = column_name
    to_df[newcol] = 0
    tmp = from_df[['ab_id', column_name]]
    
    for i in range(len(atbatidlist)):
        atbatid = np.array(atbatidlist)[i]
        val = tmp.loc[tmp['ab_id']==atbatid, newcol]
        val = np.array(val)[0]
        to_df.loc[to_df['ab_id']==atbatid, newcol] = val
        
    return to_df

In [26]:
#copy data
mypitches = copyData(atbats_pitcher, mypitches, atbat_id, 'stand')
mypitches = copyData(atbats_pitcher, mypitches, atbat_id, 'inning')
mypitches = copyData(atbats_pitcher, mypitches, atbat_id, 'p_score')

## ONE HOT ENCODING

In [27]:
#one hot encode columns (pitch result ('type') and batter handedness ('stand'))
mypitches = pd.get_dummies(mypitches, columns=['type','stand'])
mypitches

,px,pz,end_speed,pitch_type,b_score,ab_id,b_count,s_count,outs,pitch_num,on_1b,on_2b,on_3b,pitch_type_code,year,inning,p_score,type_B,type_S,type_X,stand_L,stand_R
2407,-1.598000,1.869000,82.8,1,0.0,2015000632,0.0,0.0,0.0,1.0,0.0,0.0,0.0,FB,2015,1,0,0,1,0,1,0
2408,-0.909000,2.487000,85.0,1,0.0,2015000632,0.0,1.0,0.0,2.0,0.0,0.0,0.0,FB,2015,1,0,0,1,0,1,0
2409,-1.585000,2.934000,86.6,1,0.0,2015000632,0.0,2.0,0.0,3.0,0.0,0.0,0.0,FB,2015,1,0,1,0,0,1,0
2410,0.364000,0.245000,79.9,3,0.0,2015000632,1.0,2.0,0.0,4.0,0.0,0.0,0.0,OS,2015,1,0,1,0,0,1,0
2411,-1.927000,4.250000,85.7,1,0.0,2015000632,2.0,2.0,0.0,5.0,0.0,0.0,0.0,FB,2015,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843321,-0.176597,2.767898,89.0,1,1.0,2018179463,3.0,2.0,1.0,8.0,0.0,0.0,0.0,FB,2018,7,3,0,1,0,0,1
2843322,-0.177377,2.792270,87.8,1,1.0,2018179463,3.0,2.0,1.0,9.0,0.0,0.0,0.0,FB,2018,7,3,0,1,0,0,1
2843323,0.167994,1.369971,78.8,2,1.0,2018179463,3.0,2.0,1.0,10.0,0.0,0.0,0.0,BR,2018,7,3,0,1,0,0,1
2843324,0.206482,2.114205,86.1,1,1.0,2018179464,0.0,0.0,2.0,1.0,0.0,0.0,0.0,FB,2018,7,3,0,0,1,1,0
2843325,-0.475813,2.339857,76.6,3,1.0,2018179465,0.0,0.0,2.0,1.0,1.0,0.0,0.0,OS,2018,7,3,0,0,1,1,0

# WRITE OUT DATA

In [28]:
output = mypitches
output.to_csv('PitcherData.csv', index=False)